/**
 * Cipher Scramble word library.
 * Organized by category — players pick which packs to pull from.
 * No third-party franchise names (Pokémon etc. are trademarked).
 */

export type WordTier = "easy" | "mid" | "hard";

export type WordCategoryId =
  | "merkvex"
  | "cyberpunk"
  | "space"
  | "market"
  | "tech"
  | "arcade"
  | "animals"
  | "nature"
  | "food"
  | "everyday";

export type WordEntry = {
  word: string;
  hint: string;
  tier: WordTier;
  category: WordCategoryId;
};

export type CategoryMeta = {
  id: WordCategoryId;
  label: string;
  blurb: string;
  accent: "electric" | "cyan" | "violet" | "mint";
};

export const CATEGORIES: CategoryMeta[] = [
  { id: "merkvex", label: "Neon Brand", blurb: "Arcade brand words", accent: "electric" },
  { id: "cyberpunk", label: "Cyberpunk", blurb: "Net, chrome, corps", accent: "cyan" },
  { id: "space", label: "Space", blurb: "Orbit, stars, void", accent: "violet" },
  { id: "market", label: "Trade", blurb: "Buy, sell, tokens", accent: "electric" },
  { id: "tech", label: "Tech", blurb: "Code, systems, data", accent: "cyan" },
  { id: "arcade", label: "Arcade", blurb: "Games, scores, play", accent: "electric" },
  { id: "animals", label: "Animals", blurb: "Creatures (original)", accent: "mint" },
  { id: "nature", label: "Nature", blurb: "Earth, weather, wild", accent: "mint" },
  { id: "food", label: "Food", blurb: "Snacks & kitchen", accent: "violet" },
  { id: "everyday", label: "Everyday", blurb: "Common English", accent: "cyan" },
];

function w(
  word: string,
  hint: string,
  tier: WordTier,
  category: WordCategoryId,
): WordEntry {
  return { word: word.toUpperCase(), hint, tier, category };
}

export const WORD_BANK: WordEntry[] = [
  // ── Merkvex ──────────────────────────────────────────────
  w("MERKVEX", "This arcade's brand", "easy", "merkvex"),
  w("VOID", "Deep purple brand color", "easy", "merkvex"),
  w("VAULT", "Where value is locked", "easy", "merkvex"),
  w("DECK", "Card stack you run", "easy", "merkvex"),
  w("AGENT", "Character on the board", "easy", "merkvex"),
  w("PILOT", "Default callsign", "easy", "merkvex"),
  w("SPARK", "Electric yellow energy", "easy", "merkvex"),
  w("NEON", "Glow of the night market", "easy", "merkvex"),
  w("TOKEN", "On-chain unit of value", "easy", "merkvex"),
  w("RARE", "Above uncommon", "easy", "merkvex"),
  w("MYTHIC", "Near the top rarity", "mid", "merkvex"),
  w("LEGEND", "Rarity just under mythic", "mid", "merkvex"),
  w("HANDLER", "Street-level agent job", "mid", "merkvex"),
  w("COURIER", "Runs the sub-net", "mid", "merkvex"),
  w("WEAVER", "Threads circuits", "mid", "merkvex"),
  w("SOVEREIGN", "Apex title", "hard", "merkvex"),
  w("SINGULARITY", "Chimera's domain", "hard", "merkvex"),
  w("CHIMERA", "Legendary multi-form", "mid", "merkvex"),
  w("AXOLOTL", "Bio-luminescent agent", "mid", "merkvex"),
  w("PRISM", "Splits light into color", "easy", "merkvex"),
  w("ARCHWEAVE", "Master handler craft", "hard", "merkvex"),
  w("SPLICE", "Fox-style gene mix", "mid", "merkvex"),
  w("KIOSK", "Clerk's little booth", "easy", "merkvex"),
  w("PATCH", "Hacker who hotfixes live", "easy", "merkvex"),
  w("BEETLE", "Spark bug agent", "easy", "merkvex"),
  w("SLIME", "Pocket goo companion", "easy", "merkvex"),
  w("LYNX", "Crystal prism cat", "easy", "merkvex"),
  w("NAVIGATOR", "Void pilot specialty", "mid", "merkvex"),
  w("HATCHLING", "Young eclipse dragon", "mid", "merkvex"),
  w("EXECUTIVE", "Black-gold operator rank", "mid", "merkvex"),
  w("CALLSIGN", "Name on the board", "mid", "merkvex"),
  w("RARITY", "How scarce a card is", "mid", "merkvex"),
  w("COMMON", "Most frequent drop", "easy", "merkvex"),
  w("UNCOMMON", "A step above common", "mid", "merkvex"),

  // ── Cyberpunk ────────────────────────────────────────────
  w("CYBER", "Digital + punk prefix", "easy", "cyberpunk"),
  w("FIREWALL", "Blocks bad packets", "mid", "cyberpunk"),
  w("PAYLOAD", "What the exploit carries", "mid", "cyberpunk"),
  w("BACKDOOR", "Hidden access path", "mid", "cyberpunk"),
  w("ROOTKIT", "Hides deep in the system", "hard", "cyberpunk"),
  w("ZERODAY", "Exploit nobody patched", "mid", "cyberpunk"),
  w("GLITCH", "Unexpected system stutter", "easy", "cyberpunk"),
  w("ENCRYPT", "Scramble so only keys read", "mid", "cyberpunk"),
  w("DECRYPT", "Undo the scramble", "mid", "cyberpunk"),
  w("PHANTOM", "Ghost in the machine", "mid", "cyberpunk"),
  w("MEGACORP", "Company bigger than states", "mid", "cyberpunk"),
  w("RUNNER", "Net operator for hire", "easy", "cyberpunk"),
  w("FIXER", "Connects jobs to talent", "easy", "cyberpunk"),
  w("CRED", "Reputation + cash slang", "easy", "cyberpunk"),
  w("IMPLANT", "Chrome under the skin", "mid", "cyberpunk"),
  w("CHROME", "Visible cyberware shine", "easy", "cyberpunk"),
  w("WETWARE", "Meat-side of the stack", "mid", "cyberpunk"),
  w("NEURAL", "Of the mind link", "easy", "cyberpunk"),
  w("UPLINK", "Connection outbound", "easy", "cyberpunk"),
  w("BLACKICE", "Lethal countermeasure", "mid", "cyberpunk"),
  w("MAINFRAME", "Central computing beast", "mid", "cyberpunk"),
  w("JACKIN", "Plug into the net", "mid", "cyberpunk"),
  w("ICEWALL", "Hostile security layer", "mid", "cyberpunk"),
  w("DATALAKE", "Huge pool of raw info", "mid", "cyberpunk"),
  w("OVERCLOCK", "Push hardware past rating", "hard", "cyberpunk"),
  w("HOLOGRAM", "Floating light image", "mid", "cyberpunk"),
  w("ANDROID", "Synthetic human form", "mid", "cyberpunk"),
  w("SYNTH", "Artificial / electronic", "easy", "cyberpunk"),
  w("CLOAK", "Become hard to see", "easy", "cyberpunk"),
  w("TRACE", "Follow a signal home", "easy", "cyberpunk"),
  w("OVERRIDE", "Force past a control", "mid", "cyberpunk"),
  w("NIGHTCITY", "Neon metropolis vibe", "hard", "cyberpunk"),
  w("STREETSAM", "Blade-for-hire slang", "hard", "cyberpunk"),
  w("NETWATCH", "Corporate net police vibe", "mid", "cyberpunk"),
  w("GRID", "The connected world", "easy", "cyberpunk"),
  w("NOISE", "Static on the line", "easy", "cyberpunk"),

  // ── Space ─────────────────────────────────────────────────
  w("ORBIT", "Path around a body", "easy", "space"),
  w("SATELLITE", "Machine in orbit", "mid", "space"),
  w("HORIZON", "Where sky meets ground", "mid", "space"),
  w("ECLIPSE", "Light blocked by shadow", "mid", "space"),
  w("NEBULA", "Cosmic cloud of gas", "mid", "space"),
  w("PULSAR", "Spinning radio star", "mid", "space"),
  w("QUASAR", "Bright distant engine", "mid", "space"),
  w("COMET", "Icy traveler with a tail", "easy", "space"),
  w("ASTEROID", "Rocky belt traveler", "mid", "space"),
  w("GALAXY", "Island of stars", "easy", "space"),
  w("COSMOS", "The whole universe", "mid", "space"),
  w("ROCKET", "Leaves the pad fast", "easy", "space"),
  w("THRUSTER", "Pushes a craft forward", "mid", "space"),
  w("AIRLOCK", "Door between air and void", "mid", "space"),
  w("SPACESUIT", "Wearable life support", "hard", "space"),
  w("TELEPORT", "Instant relocation fantasy", "mid", "space"),
  w("WORMHOLE", "Shortcut through space", "hard", "space"),
  w("BLACKHOLE", "Gravity that eats light", "hard", "space"),
  w("STARSHIP", "Vessel between worlds", "mid", "space"),
  w("LUNAR", "Of the moon", "easy", "space"),
  w("SOLAR", "Of the sun", "easy", "space"),
  w("METEOR", "Streak across the sky", "easy", "space"),
  w("PLASMA", "Hot ionized glow", "mid", "space"),
  w("GRAVITY", "What keeps you down", "mid", "space"),
  w("VACUUM", "Empty space between stars", "mid", "space"),
  w("LAUNCH", "Leave the ground", "easy", "space"),
  w("DOCKING", "Link two craft together", "mid", "space"),
  w("PROBE", "Uncrewed explorer", "easy", "space"),
  w("HABITAT", "Place to live off-world", "mid", "space"),
  w("STARLIGHT", "Glow from distant suns", "mid", "space"),

  // ── Market / trade ───────────────────────────────────────
  w("TRADE", "What the floor is for", "easy", "market"),
  w("BOARD", "Market surface", "easy", "market"),
  w("CHIP", "Silicon currency cousin", "easy", "market"),
  w("WALLET", "Holds keys and balance", "easy", "market"),
  w("LEDGER", "Immutable record of trades", "mid", "market"),
  w("AIRDROP", "Free tokens from the sky", "mid", "market"),
  w("STAKING", "Lock value to earn yield", "mid", "market"),
  w("LIQUIDITY", "How easy it is to trade", "hard", "market"),
  w("ARBITRAGE", "Profit from price gaps", "hard", "market"),
  w("VOLATILITY", "How wild prices swing", "hard", "market"),
  w("BLUECHIP", "Trusted high-value asset", "mid", "market"),
  w("WHITELIST", "Approved access list", "mid", "market"),
  w("BID", "What a buyer offers", "easy", "market"),
  w("ASK", "What a seller wants", "easy", "market"),
  w("SPREAD", "Gap between bid and ask", "mid", "market"),
  w("FLOOR", "Lowest list price vibe", "easy", "market"),
  w("BULL", "Market that runs up", "easy", "market"),
  w("BEAR", "Market that runs down", "easy", "market"),
  w("PUMP", "Sudden price surge slang", "easy", "market"),
  w("DUMP", "Sudden price drop slang", "easy", "market"),
  w("MINT", "Create a new asset", "easy", "market"),
  w("BURN", "Destroy supply on purpose", "easy", "market"),
  w("YIELD", "Return on locked value", "easy", "market"),
  w("PORTFOLIO", "Your collection of assets", "mid", "market"),
  w("ESCROW", "Neutral hold until done", "mid", "market"),
  w("AUCTION", "Highest bidder wins", "mid", "market"),
  w("LISTING", "Offer to sell now", "mid", "market"),
  w("SETTLE", "Finalize a trade", "mid", "market"),
  w("PREMIUM", "Price above the pack", "mid", "market"),
  w("DISCOUNT", "Price below the pack", "mid", "market"),

  // ── Tech ─────────────────────────────────────────────────
  w("SIGNAL", "Wave carrying data", "easy", "tech"),
  w("LATENCY", "Delay on the line", "mid", "tech"),
  w("BANDWIDTH", "How much data fits", "mid", "tech"),
  w("HASH", "One-way fingerprint of data", "easy", "tech"),
  w("NODE", "Point on a network", "easy", "tech"),
  w("SUBNET", "Sliced network segment", "mid", "tech"),
  w("PROXY", "Middleman for traffic", "easy", "tech"),
  w("TERMINAL", "Where you type commands", "mid", "tech"),
  w("KERNEL", "Core of the OS", "mid", "tech"),
  w("SANDBOX", "Isolated test space", "mid", "tech"),
  w("PROTOCOL", "Rules machines speak", "mid", "tech"),
  w("PACKET", "Tiny unit of network data", "mid", "tech"),
  w("BUFFER", "Temporary holding area", "easy", "tech"),
  w("CACHE", "Fast local copy", "easy", "tech"),
  w("PIXEL", "Single light on screen", "easy", "tech"),
  w("RENDER", "Turn data into image", "easy", "tech"),
  w("VECTOR", "Math with direction", "mid", "tech"),
  w("MATRIX", "Grid of numbers", "mid", "tech"),
  w("BINARY", "Ones and zeros", "easy", "tech"),
  w("CIPHER", "Secret writing system", "mid", "tech"),
  w("DEBUG", "Hunt and fix bugs", "easy", "tech"),
  w("COMPILE", "Turn source into binary", "mid", "tech"),
  w("RUNTIME", "When the program is live", "mid", "tech"),
  w("CHECKSUM", "Integrity number for data", "mid", "tech"),
  w("HANDSHAKE", "Two systems greeting", "mid", "tech"),
  w("REBOOT", "Power cycle the system", "easy", "tech"),
  w("BOOT", "Cold start the machine", "easy", "tech"),
  w("LOGIN", "Prove who you are", "easy", "tech"),
  w("ADMIN", "Highest access role", "easy", "tech"),
  w("ROOT", "Superuser privilege", "easy", "tech"),
  w("SERVER", "Machine that serves others", "easy", "tech"),
  w("CLIENT", "Machine that asks", "easy", "tech"),
  w("API", "How apps talk", "easy", "tech"),
  w("CLOUD", "Someone else's computers", "easy", "tech"),
  w("THREAD", "Parallel unit of work", "mid", "tech"),
  w("MEMORY", "Where programs hold state", "easy", "tech"),
  w("STORAGE", "Where data sleeps", "mid", "tech"),
  w("ROUTER", "Directs traffic on a net", "mid", "tech"),
  w("SWITCH", "Links devices in a LAN", "mid", "tech"),
  w("FIRMWARE", "Code close to hardware", "mid", "tech"),
  w("DRIVER", "Talks to a device", "mid", "tech"),
  w("QUANTUM", "Physics of weird bits", "mid", "tech"),
  w("CIRCUIT", "Path electricity follows", "mid", "tech"),
  w("VOLTAGE", "Electric pressure", "mid", "tech"),
  w("SENSOR", "Reads the world", "easy", "tech"),
  w("DRONE", "Uncrewed flyer", "easy", "tech"),
  w("ROBOT", "Programmable machine", "easy", "tech"),
  w("LASER", "Coherent light beam", "easy", "tech"),

  // ── Arcade ───────────────────────────────────────────────
  w("ARCADE", "Where you are right now", "easy", "arcade"),
  w("CABINET", "Machine that holds a game", "mid", "arcade"),
  w("HIGHSCORE", "Best number on the board", "mid", "arcade"),
  w("GAMEOVER", "Session ended", "mid", "arcade"),
  w("CONTINUE", "Insert coin prompt", "mid", "arcade"),
  w("LEVELUP", "Power increase ding", "mid", "arcade"),
  w("BOSS", "Big challenge at the end", "easy", "arcade"),
  w("COMBO", "Chain of good hits", "easy", "arcade"),
  w("CRITICAL", "Lucky high-damage strike", "mid", "arcade"),
  w("SHIELD", "Blocks incoming harm", "easy", "arcade"),
  w("ENERGY", "What pods restore", "easy", "arcade"),
  w("BLAST", "Sudden burst attack", "easy", "arcade"),
  w("DASH", "Short burst of speed", "easy", "arcade"),
  w("JUMP", "Leave the platform", "easy", "arcade"),
  w("GLIDE", "Controlled fall", "easy", "arcade"),
  w("HOVER", "Stay aloft without thrust", "easy", "arcade"),
  w("WARP", "Skip space between points", "easy", "arcade"),
  w("PHASE", "Shift through matter", "easy", "arcade"),
  w("SCAN", "Sweep for information", "easy", "arcade"),
  w("LOCKON", "Target acquired", "mid", "arcade"),
  w("POWERUP", "Temporary boost item", "mid", "arcade"),
  w("RESPAWN", "Come back after a wipe", "mid", "arcade"),
  w("CHECKPOINT", "Safe progress marker", "mid", "arcade"),
  w("LEADERBOARD", "Who sits on top", "hard", "arcade"),
  w("MULTIPLAYER", "More than one pilot", "hard", "arcade"),
  w("TUTORIAL", "Learn before you burn", "mid", "arcade"),
  w("DIFFICULTY", "How mean the game is", "mid", "arcade"),
  w("PIXELART", "Blocky classic look", "mid", "arcade"),
  w("JOYSTICK", "Stick you push around", "mid", "arcade"),
  w("BUTTON", "Mash for action", "easy", "arcade"),
  w("COIN", "Classic insert fuel", "easy", "arcade"),
  w("BONUS", "Extra points round", "easy", "arcade"),
  w("LIVES", "How many tries remain", "easy", "arcade"),
  w("STREAK", "Unbroken win chain", "easy", "arcade"),
  w("PONG", "Yes, still here", "easy", "arcade"),
  w("PING", "Are you there?", "easy", "arcade"),

  // ── Animals (original / generic — not franchise) ─────────
  w("FOX", "Clever red hunter", "easy", "animals"),
  w("WOLF", "Pack howler", "easy", "animals"),
  w("LYNX", "Tufted-ear wildcat", "easy", "animals"),
  w("OWL", "Night hunter of silence", "easy", "animals"),
  w("RAVEN", "Dark clever bird", "easy", "animals"),
  w("FALCON", "Dive-speed raptor", "mid", "animals"),
  w("DRAGON", "Mythic fire lizard", "easy", "animals"),
  w("PHOENIX", "Bird that rises from ash", "mid", "animals"),
  w("SERPENT", "Long coiling reptile", "mid", "animals"),
  w("PANTHER", "Sleek dark big cat", "mid", "animals"),
  w("TIGER", "Striped big cat", "easy", "animals"),
  w("EAGLE", "National sky hunter", "easy", "animals"),
  w("SHARK", "Ocean apex swimmer", "easy", "animals"),
  w("WHALE", "Giant of the deep", "easy", "animals"),
  w("DOLPHIN", "Playful ocean mind", "mid", "animals"),
  w("OCTOPUS", "Eight-armed genius", "mid", "animals"),
  w("JELLYFISH", "Soft stinging drifter", "mid", "animals"),
  w("MANTIS", "Praying insect hunter", "mid", "animals"),
  w("BEETLE", "Hard-shelled bug", "easy", "animals"),
  w("SPIDER", "Eight-legged weaver", "easy", "animals"),
  w("SNAKE", "Limbless reptile", "easy", "animals"),
  w("FROG", "Hopping amphibian", "easy", "animals"),
  w("TURTLE", "Shell on the move", "easy", "animals"),
  w("RABBIT", "Long-eared hopper", "easy", "animals"),
  w("OTTER", "Playful river weasel", "easy", "animals"),
  w("BADGER", "Striped burrower", "mid", "animals"),
  w("MOOSE", "Antlered giant", "easy", "animals"),
  w("BISON", "Shaggy plains beast", "mid", "animals"),
  w("COYOTE", "Desert song dog", "mid", "animals"),
  w("HAWK", "Daytime sky hunter", "easy", "animals"),
  w("CRANE", "Tall elegant wader", "easy", "animals"),
  w("KOALA", "Eucalyptus sleeper", "easy", "animals"),
  w("PANDA", "Bamboo black-and-white", "easy", "animals"),
  w("LEMUR", "Ring-tailed climber", "mid", "animals"),
  w("GECKO", "Sticky-footed lizard", "easy", "animals"),

  // ── Nature ───────────────────────────────────────────────
  w("FOREST", "Many trees together", "easy", "nature"),
  w("RIVER", "Fresh water on the move", "easy", "nature"),
  w("OCEAN", "Salt water world", "easy", "nature"),
  w("MOUNTAIN", "High stone peak", "mid", "nature"),
  w("VALLEY", "Low land between peaks", "mid", "nature"),
  w("DESERT", "Dry sand expanse", "easy", "nature"),
  w("GLACIER", "Slow river of ice", "mid", "nature"),
  w("VOLCANO", "Mountain that erupts", "mid", "nature"),
  w("THUNDER", "Sound after lightning", "mid", "nature"),
  w("LIGHTNING", "Sky's electric bolt", "mid", "nature"),
  w("RAINBOW", "Arc of broken light", "mid", "nature"),
  w("AURORA", "Polar light curtain", "mid", "nature"),
  w("BLOSSOM", "Flower opening", "mid", "nature"),
  w("MEADOW", "Open grassy field", "mid", "nature"),
  w("CANYON", "Deep cut in the earth", "mid", "nature"),
  w("ISLAND", "Land in water", "easy", "nature"),
  w("CORAL", "Reef builder", "easy", "nature"),
  w("MOSS", "Soft green carpet", "easy", "nature"),
  w("CEDAR", "Fragrant evergreen", "easy", "nature"),
  w("WILLOW", "Weeping tree", "easy", "nature"),
  w("STORM", "Wild weather system", "easy", "nature"),
  w("BREEZE", "Gentle wind", "easy", "nature"),
  w("FROST", "Cold white coat", "easy", "nature"),
  w("EMBER", "Glowing coal", "easy", "nature"),
  w("CRYSTAL", "Ordered solid beauty", "mid", "nature"),
  w("GEYSER", "Hot water fountain", "mid", "nature"),
  w("TUNDRA", "Cold open plain", "mid", "nature"),
  w("JUNGLE", "Dense wet forest", "easy", "nature"),
  w("SAVANNA", "Warm grass plain", "mid", "nature"),
  w("LAGOON", "Shallow coastal pool", "mid", "nature"),

  // ── Food ─────────────────────────────────────────────────
  w("PIZZA", "Cheesy round classic", "easy", "food"),
  w("SUSHI", "Rice and raw art", "easy", "food"),
  w("TACO", "Folded handheld meal", "easy", "food"),
  w("NOODLE", "Long dough strand", "easy", "food"),
  w("RAMEN", "Broth and noodles", "easy", "food"),
  w("BURGER", "Stacked sandwich", "easy", "food"),
  w("WAFFLE", "Grid breakfast cake", "easy", "food"),
  w("PANCAKE", "Flat griddle cake", "mid", "food"),
  w("COOKIE", "Sweet bite", "easy", "food"),
  w("MUFFIN", "Cup-shaped bake", "easy", "food"),
  w("BAGEL", "Boiled then baked ring", "easy", "food"),
  w("PRETZEL", "Twisted salty snack", "mid", "food"),
  w("POPCORN", "Exploded corn", "mid", "food"),
  w("CHOCOLATE", "Cacao treat", "mid", "food"),
  w("VANILLA", "Classic pale flavor", "mid", "food"),
  w("CINNAMON", "Warm bark spice", "mid", "food"),
  w("GINGER", "Spicy root", "easy", "food"),
  w("PEPPER", "Heat or color spice", "easy", "food"),
  w("GARLIC", "Pungent bulb", "easy", "food"),
  w("HONEY", "Bee-made sweetness", "easy", "food"),
  w("MAPLE", "Tree syrup flavor", "easy", "food"),
  w("LEMON", "Sour yellow citrus", "easy", "food"),
  w("MANGO", "Tropical gold fruit", "easy", "food"),
  w("BERRY", "Small juicy fruit", "easy", "food"),
  w("PEACH", "Fuzzy summer fruit", "easy", "food"),
  w("AVOCADO", "Green cream fruit", "mid", "food"),
  w("TOFU", "Bean curd block", "easy", "food"),
  w("CURRY", "Spiced sauce dish", "easy", "food"),
  w("DUMPLING", "Filled dough pocket", "mid", "food"),
  w("NOUGAT", "Chewy candy center", "mid", "food"),
  w("SORBET", "Icy fruit dessert", "mid", "food"),
  w("SMOOTHIE", "Blended fruit drink", "mid", "food"),
  w("ESPRESSO", "Strong short coffee", "mid", "food"),
  w("LATTE", "Milk-forward coffee", "easy", "food"),
  w("MATCHA", "Green tea powder", "easy", "food"),

  // ── Everyday ─────────────────────────────────────────────
  w("WINDOW", "Glass in a wall", "easy", "everyday"),
  w("MIRROR", "Reflects your face", "easy", "everyday"),
  w("POCKET", "Small cloth stash", "easy", "everyday"),
  w("BUTTON", "Fastens a shirt", "easy", "everyday"),
  w("JACKET", "Outer layer", "easy", "everyday"),
  w("SNEAKER", "Casual shoe", "mid", "everyday"),
  w("BACKPACK", "Carry on your back", "mid", "everyday"),
  w("UMBRELLA", "Rain shield", "mid", "everyday"),
  w("LANTERN", "Portable light", "mid", "everyday"),
  w("BRIDGE", "Path over a gap", "easy", "everyday"),
  w("TUNNEL", "Path under ground", "easy", "everyday"),
  w("STATION", "Where trains stop", "mid", "everyday"),
  w("TICKET", "Proof you may enter", "easy", "everyday"),
  w("PASSPORT", "Border identity book", "mid", "everyday"),
  w("LIBRARY", "House of books", "mid", "everyday"),
  w("MUSEUM", "House of exhibits", "mid", "everyday"),
  w("THEATER", "House of shows", "mid", "everyday"),
  w("KITCHEN", "Where food is made", "mid", "everyday"),
  w("GARDEN", "Plants you tend", "easy", "everyday"),
  w("BALCONY", "Outdoor shelf of a home", "mid", "everyday"),
  w("ELEVATOR", "Box that goes up", "mid", "everyday"),
  w("STAIRCASE", "Steps between floors", "mid", "everyday"),
  w("NOTEBOOK", "Pages for ideas", "mid", "everyday"),
  w("PENCIL", "Graphite writer", "easy", "everyday"),
  w("MARKER", "Bold ink stick", "easy", "everyday"),
  w("CALENDAR", "Days on a grid", "mid", "everyday"),
  w("CLOCK", "Tells the time", "easy", "everyday"),
  w("ALARM", "Wakes you up", "easy", "everyday"),
  w("PILLOW", "Soft head rest", "easy", "everyday"),
  w("BLANKET", "Warm cover", "easy", "everyday"),
  w("CANDLE", "Wax light", "easy", "everyday"),
  w("GUITAR", "Six-string music", "easy", "everyday"),
  w("PIANO", "Keys that sing", "easy", "everyday"),
  w("CAMERA", "Captures a moment", "easy", "everyday"),
  w("BATTERY", "Portable power", "mid", "everyday"),
  w("CHARGER", "Refills the battery", "mid", "everyday"),
  w("HEADPHONE", "Sound for your ears", "mid", "everyday"),
  w("MESSAGE", "Words sent to someone", "mid", "everyday"),
  w("FRIEND", "Person you trust", "easy", "everyday"),
  w("FAMILY", "People you came from", "easy", "everyday"),
];

export const ALL_CATEGORY_IDS: WordCategoryId[] = CATEGORIES.map((c) => c.id);

export function wordsInCategories(cats: Iterable<WordCategoryId>): WordEntry[] {
  const set = new Set(cats);
  if (set.size === 0) return WORD_BANK;
  return WORD_BANK.filter((w) => set.has(w.category));
}

export function categoryWordCount(id: WordCategoryId): number {
  return WORD_BANK.filter((w) => w.category === id).length;
}

export function pickWord(
  used: Set<string>,
  opts?: {
    prefer?: WordTier;
    categories?: Iterable<WordCategoryId>;
  },
): WordEntry {
  const pool0 = wordsInCategories(opts?.categories ?? ALL_CATEGORY_IDS);
  let pool = pool0.filter((w) => !used.has(w.word));
  if (opts?.prefer) {
    const tiered = pool.filter((w) => w.tier === opts.prefer);
    if (tiered.length) pool = tiered;
  }
  if (!pool.length) pool = pool0.length ? pool0 : WORD_BANK;
  return pool[Math.floor(Math.random() * pool.length)]!;
}
